### ISSUE TITLE
vertica-go-sql connector hangs when processing failed exec command. 

### ISSUE THREAD

**Issue by klwilson227** [vertica/vertica-sql-go#79] opened 2020-03-21 17:00 UTC
This is a bit of a complex test but none the less it fails predictably.  

Situation is that during the development of a UDX Source plugin we found that simply throwing an error from the UDSouce::processWithMetadata function causes the vertica-go-client to never return from the call and hangs the session. 

// The below implementation on the source causes the vertica go client to hang indefinitely. 
StreamState TestSource::processWithMetadata(ServerInterface &srvInterface, DataBuffer &output,
                                              LengthBuffer &output_lengths)
{
    vt_report_error(2, "FORCE process with Metadata error");
    return StreamState::DONE;
}

Now we use the vertica-go-sql sample app thats provided with the appropriate connection string changed. Plus the following additional snippet... 

// Query a standard metric table in Vertica.
    _, err = connDB.ExecContext(ctx, "COPY public.from_test SOURCE TestSource() PARSER KafkaJSONParser(flatten_arrays=True, flatten_maps=True) DIRECT NO COMMIT;")

    if err != nil {
        testLogger.Fatal(err.Error())
        os.Exit(1)
    }
    testLogger.Info("Test complete")

Running the above snippet from vsql, the proper error is returned every time and no hangs. 
And the vertica.log file shows that the TestSource was executed and returns with same logs as when executed from the vsql command.
[testudx.tar.gz](https://github.com/vertica/vertica-sql-go/files/4363384/testudx.tar.gz)

**Comment by klwilson227** [comment] 2020-03-21 17:16
NOTE: I reproduced the same results against vertica versions 9.2.0, 9.2.1, and 9.3.0.

**Comment by klwilson227** [comment] 2020-03-21 19:09
When inspecting the go stack trace.. the error appears to be in that the Close() stmt.go:124 is expecting a message response from the server with either a type=msg.BECloseCompleteMsg to exit the loop, bu no message is ever received in this case. But a message is never sent from Vertica.

**Comment by klwilson227** [comment] 2020-03-21 19:43
Possible patch to this issue it to set s.rollback = true. Which allows the close logic to exit gracefully when a error is reported from the Exec command.

// ExecContext docs
func (s *stmt) ExecContext(ctx context.Context, args []driver.NamedValue) (driver.Result, error) {
	stmtLogger.Trace("stmt.ExecContext()")

	rows, err := s.QueryContext(ctx, args)

	if err != nil {
		s.rolledBack = true
		return driver.ResultNoRows, err
	}

**Comment by huebnerr** [comment] 2020-03-21 20:18
@klwilson227, I'm worried this issue might manifest in other ways. Since it would be kind of tricky to replicate outside of your environment, could you check to see if there are some other messages getting ignored in the process? For example, inside of the Close() method, can you call defaultMessageHandler() to log any other conditions?

**Comment by klwilson227** [comment] 2020-03-21 21:30
I have replicated this issue already in 3 different vertica environments including the community 9.3 bits that I pulled down about 8 weeks ago. I realize that compiling and deploying the .so from the vertica go test infrastructure; adds a bit to the complexity but it has been very simple to replicate after loading the SO by hand. The so is very stupid as well in that it is configured to always throw the error, the interesting part is how vertica-go-sql treats this error response. 

I believe this issue would replicate in hundreds of different scenarios in which the vt_report_error api is call either internally by vertica code or externally via a UDX plugin. You can likely reproduce the issue on any of the vertica provided UDX plugins, by giving them what appears to be a valid configuration, but one that has a operational/runtime reported issue. For example, try the same with the KafkaSource, and give it a kafka endpoint that is invalid.  This could simplify the testing scenario but complicate the UDX plugin used. 

From what I have seen in the tracing this is not a matter of miss handling of messages but a matter of never receiving a response to the close message that is issued during the Close() method. I see two bind messages come in prior to simply running out of data responses. 

By setting the rolledBack, I am avoiding the close message being sent. And thus the code no longer gets stuck here. I am a novice at the wire protocol used by vertica. But something certainly is not in alignment here, and I hope those whom know better can make a decisions on what the right course of action should be to resolve this issue.  The work around/solution I proposed I will have more formally in a  PR once, I can get the test environment running.

**Comment by huebnerr** [comment] 2020-03-21 21:38
Would also ask @sitingren and @tomwall to have a look at this. @sitingren is on the vertica-python driver and @tomwall is master of all things Vertica.

**Comment by sitingren** [comment] 2020-03-23 10:27
Could you please provide the log file of executing your Go program? I'd like to see the wire protocol communication messages btw the server and vertica-sql-go. Thanks!

**Comment by tomwall** [comment] 2020-03-23 17:19
Kevin and I discussed offline; this seems like a general problem with how the client responds to certain kinds of errors. You can reproduce with a much simpler query: select throw_error('whatever').

I suspect it may be specific to errors that pass the syntax/semantic checks but fail at execution time. In other words, the query/bind+exec message is accepted by the database, the database does semantic analysis and it sends back the row description for the result, but then at execution time the error response is sent where you'd usually see row data / command complete instead. 

If the client does a read expecting a certain message that will never arrive, like a row or command complete, then it will get stuck. If that's whats happening the client should issue a sync and then seek until it gets the RFQ. Before packaging up that error and returning it to the application.

**Comment by huebnerr** [comment] 2020-03-23 20:19
Interesting. I've seen that pattern once before and fixed it with a simple catch and a call to sync(). I think it was in the Parse/Describe phases. It seems it can happen in the Bind/Execute sides as well.
Tonight I'll have a look at fixing this in a consistent manner.

**Comment by huebnerr** [comment] 2020-03-23 20:50
It looked line a one-liner. Please check https://github.com/vertica/vertica-sql-go/tree/huebnerr-lock-on-error

**Comment by klwilson227** [comment] 2020-03-24 13:42
Will get this done as soon as I can.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by huebnerr** [comment] 2020-03-26 14:57
Addressed in https://github.com/vertica/vertica-sql-go/pull/80

**Closed by huebnerr** 2020-03-26 14:57 UTC
Labels: bug
